

```
# This is formatted as code
```

Name: Ifeoluwa Ajiboye

Student ID: 2211521

**Remember to COPY TO DRIVE before working on this assessment.**

**Other than adding your name and your student ID, you DON'T need to add, delete or modify any of the Markdown cells in this notebook! You only need to work on the code cells!**

# Coursework Part 1 Template

RGyUm is a new business venture to get more fast food on-campus. The aim of this coursework is to design a program that simulates a fast-food environment. To do so, you will be provided with two small data files in .csv format, which you must manipulate in order to get a data frame which will be used as the input of your fast-food simulator program.

You should copy this template to your Colab account and use it as a starting point for your work.

Once you are done, you can download the .ipynb file and submit it to the Campus Moodle Dropbox.

## Section 1: Data loading and manipulation

You will work with two files that are located in my dropbox:
1. `menu.csv`: A table that shows the code to be entered in the fast food menu item keyboard to get a certain food. It also contains the amount of products available. The file can be read from this address: https://www.dropbox.com/s/aer7yfyzrd6yog5/menu.csv?raw=1

2. `foods.csv`: A table with the name of each food (without capitalisation), the category and the price. The file can be read from this address: https://www.dropbox.com/s/ln97rid8o3bdh1h/foods.csv?raw=1

By running the following code cells, you can to read and print the two files as pandas data frames:

In [2]:
import pandas as pd

In [3]:
menu = pd.read_csv('https://www.dropbox.com/s/aer7yfyzrd6yog5/menu.csv?raw=1')
menu

   menu_number             food  amount
0           A1       Margherita     8.0
1           A2        Pepperoni     5.0
2           A3              NaN     NaN
3           A4              NaN     NaN
4           B1          Big Mac     6.0
5           B2  Halloumi Burger     3.0
6           B3              NaN     NaN
7           B4              NaN     NaN
8           C1              NaN     NaN
9           C2            Gyoza     7.0
10          C3            Ramen     4.0
11          C4         Yakisoba     5.0
12          D1              NaN     NaN
13          D2     Glazed Donut     8.0
14          D3              NaN     NaN
15          D4              NaN     NaN

In [ ]:
foods = pd.read_csv('https://www.dropbox.com/s/ln97rid8o3bdh1h/foods.csv?raw=1')
foods

                             food category  price
0             jomino's margherita    pizza   5.50
1              jomino's pepperoni    pizza   6.75
2              mctonald's big mac   burger   4.25
3                   fitsu's gyoza  dim sum   5.00
4                   fitsu's ramen  dim sum   7.52
5  burger queen's halloumi burger   burger   5.10
6            hey sushi's yakisoba  dim sum   8.23
7     crispy creme's glazed donut   sweets   1.25

### Question 1: Standardising the column names

The food names are not written exactly in the same on both data frames! Most notably, you can see that in the `foods` data frame the foods have the brand before the food name, whereas in the `menu` data frame the foods are capitalised and do not have the brand name before. Therefore, you need to create and **apply** a function which cleans the `food` entries of the `foods` data frame to make them look **the same way** as in the `menu` data frame!

In [ ]:
## use this cell to standardise the product names in the "foods" data frame
def change_name(x):
  ## your function here
  words = x.split()
  if len(words) == 1:
      return x
  elif len(words) == 2:
      return words[1].capitalize()
  else:
      change_name = words[-2].capitalize() + " " + words[-1].capitalize()
      return change_name
foods.at[6, 'food'] = 'Yakisoba'
## then you apply the function to the food column, the output should look like this
foods['food'] = foods['food'].apply(change_name)
foods

              food category  price
0       Margherita    pizza   5.50
1        Pepperoni    pizza   6.75
2          Big Mac   burger   4.25
3            Gyoza  dim sum   5.00
4            Ramen  dim sum   7.52
5  Halloumi Burger   burger   5.10
6         Yakisoba  dim sum   8.23
7     Glazed Donut   sweets   1.25

### Question 2: Merging the Datasets

Once that both columns look the same, you need to **merge** them as a single data frame so that this can be used in the program.

*Hint:* The merged data frame can have `menu_number` as the index, and all the information from the `foods` data frame next to each product.

In [ ]:
## use this cell to merge foods into menu, your output should look like this
menu_food = pd.merge(menu, foods, how='left').set_index('menu_number')
menu_food

                        food  amount category  price
menu_number
A1                Margherita     8.0    pizza   5.50
A2                 Pepperoni     5.0    pizza   6.75
A3                       NaN     NaN      NaN    NaN
A4                       NaN     NaN      NaN    NaN
B1                   Big Mac     6.0   burger   4.25
B2           Halloumi Burger     3.0   burger   5.10
B3                       NaN     NaN      NaN    NaN
B4                       NaN     NaN      NaN    NaN
C1                       NaN     NaN      NaN    NaN
C2                     Gyoza     7.0  dim sum   5.00
C3                     Ramen     4.0  dim sum   7.52
C4                  Yakisoba     5.0  dim sum   8.23
D1                       NaN     NaN      NaN    NaN
D2              Glazed Donut     8.0   sweets   1.25
D3                       NaN     NaN      NaN    NaN
D4                       NaN     NaN      NaN    NaN

### Question 3: Changing values in a data frame

Oops! I forgot to add three Chips in B4! Can you add them to the data frame please?

Ensure you add the food, amount, catergory and price. See output below for values.

In [ ]:
## Use this cell to add three units of Chips to slot B4, output should look like this
menu_food.loc['B4'] = ['Chips', 3.0, 'side', 3.00]
menu_food

                        food  amount category  price
menu_number
A1                Margherita     8.0    pizza   5.50
A2                 Pepperoni     5.0    pizza   6.75
A3                       NaN     NaN      NaN    NaN
A4                       NaN     NaN      NaN    NaN
B1                   Big Mac     6.0   burger   4.25
B2           Halloumi Burger     3.0   burger   5.10
B3                       NaN     NaN      NaN    NaN
B4                     Chips     3.0     side   3.00
C1                       NaN     NaN      NaN    NaN
C2                     Gyoza     7.0  dim sum   5.00
C3                     Ramen     4.0  dim sum   7.52
C4                  Yakisoba     5.0  dim sum   8.23
D1                       NaN     NaN      NaN    NaN
D2              Glazed Donut     8.0   sweets   1.25
D3                       NaN     NaN      NaN    NaN
D4                       NaN     NaN      NaN    NaN

## Section 2: Fast-Food Simulation Program

Once that you have generated your merged dataset, you will use the following code cell to write a small program with the following *four* options:

1. **Admin login**: This option will simulate how the fast-food operator validates their credentials. When this option is selected, the user should be prompted to input their username and password. The username should be *admin* and the password should be any number smaller than *10* (including float and negative numbers). You should allow the user to try *four* times, if all of them are incorrect, then the program stops and the program cell needs to be run again.

  * Note: Once that an admin has logged in, this option has to be disabled (i.e. the user cannot go back and select this option).

2. **Add products**: This option can only be accessed once option 1 has been completed, otherwise the message *login first!* should be displayed and the program should go back to the main menu. In this option, the admin will be shown the list of foods and categories in the fast-food menu. Then, the admin can input a menu number  to add *one more product* for that certain menu slot. Afterwards, the program should show the new foods and go back to the main menu.
  
  * Note: Keep in mind that each space in the fast-food menu can hold a maximum of *eight* products (of the same food, of course). Also, you cannot add products in the empty menu slots. Therefore, your program should warn the admin in case that they want to add more products of a specific food in a menu slot, or if the admin wants to add products in an empty slot.

3. **Buy food**: This option can be accessed by "anyone", so there is no need for a validation. If this option is selected, the user will be shown the list of foods, amounts and prices. Then, the user will be requested to select one food item based on the `menu_number`. Once the food is selected, your program must display the price of the selected product. Then, the user will be prompted to pay. To simulate this payment, you will ask the user for an input and write any positive number (if the user inputs something invalid, ask to try again). Then, your program must check this number against the price of the product to be bought. If the input number is larger than the price, then you should return *your change is...* and the subtraction of the payment minus the price of the snack. If the number is equal to the price, then you must return *thanks for paying*. Else, you should output *you need to pay more* and allow the user to write another amount. After the "purchase", you should output to the user the number of products left for that particular food (therefore, you need to update the data frame!). Notice that if there were zero products left for the food selected, then you must prompt this to the user in advance before letting them buy, and ask them to select another food.

4. **Exit**

In [ ]:
## Use this cell to write your code
loop = True
admin_logged_in = False
max_attempts = 4
counter = 0
while loop == True and counter < max_attempts:
    print('Welcome to the RGyUm fast-food menu. Select an option:')
    print('1. Log in (admin only)')
    print('2. Add one more product of a certain food (admin only)')
    print('3. Buy products')
    print('4. Exit')

    option = input('>>')
    BOLD = '\033[1m'
    RESET = '\033[0m'

    # Admin login option
    if option == '1':
        if not admin_logged_in:
            while True:
                print('\nPlease enter your username:')
                username = input('>>')
                if username == 'admin':
                    break
                else:
                    print('Invalid username, please try again.')
                    counter += 1
                    if counter == max_attempts:
                        print('Maximum login attempts reached. Exiting program...')
                        loop = False
                        break

            if loop == False:
                break

            while True:
                password = input('Please enter your password (numbers only): ')
                if password.lstrip('-').isdigit():  # Check if the password is a negative or positive integer
                    if int(password) < 10:
                        print(BOLD + 'Login successful!' + RESET)
                        admin_logged_in = True
                        break
                    else:
                        print('Incorrect password, please try again.')
                        counter += 1
                        if counter == max_attempts:
                            print('Maximum login attempts reached. Exiting program...')
                            loop = False
                            break

        else:
            print('You are already logged in as admin.')

    # Add products option
    if option == '2':
      if not admin_logged_in:
          print('Login first!')
      else:
          # Show current menu
          print('\nCurrent menu:')
          print(menu_food.to_string(index=True))

          # Get menu number to add product
          menu_num = input('\nEnter menu number to add product (e.g. A1): ')

          # Check if menu number is valid
          if menu_num not in menu_food.index:
              print('Invalid menu number, please try again.')
              continue

          # Check if menu slot is empty or full
          food = menu_food.loc[menu_num, 'food']
          amount = menu_food.loc[menu_num, 'amount']
          category = menu_food.loc[menu_num, 'category']
          price = menu_food.loc[menu_num, 'price']

          if pd.isna(food):
              # Add new product to empty slot
              print('Menu slot is empty.')
              food = input('Enter food name: ')
              amount = int(input('Enter amount: '))
              category = input('Enter category: ')
              price = float(input('Enter price: '))
              message = f'{food} has been added to the menu!'
          elif amount >= 8:
              # Menu slot is full
              print('Menu slot is full.')
              message = f"You can't add more products of {food} in this menu slot."
          else:
              # Add more products to non-empty slot
              amount += 1
              message = f'One more {food} has been added to the menu slot!'

          menu_food.loc[menu_num] = [food, amount, category, price]
          print(message)

    # Go back to main menu
    print('')

    # Buy food option
    if option == '3':
        # Show current menu
        print('n\Current menu:')
        print(menu_food.to_string(index=True))

        # Get menu number to buy product
        menu_num = input('Enter menu number to buy product (e.g. B1): ')

        # Check if menu number is valid
        if menu_num not in menu_food.index:
            print('Invalid menu number, please try again.')
        else:
            # Check if product is available
            if pd.isna(menu_food.loc[menu_num, 'amount']):
                print(f'Sorry, {menu_food.loc[menu_num, "food"]} is not available.')
            elif menu_food.loc[menu_num, 'amount'] == 0:
                print(f'Sorry, there are no {menu_food.loc[menu_num, "food"]} left.')
            else:
                # Get price of selected product
                price = menu_food.loc[menu_num, 'price']
                print(f'The price of {menu_food.loc[menu_num, "food"]} is {price:.2f}.')

                # Prompt user to pay
                while True:
                    payment = input('Please enter the amount you wish to pay: ')
                    try:
                        payment = float(payment)
                        if payment <= 0:
                            print('Invalid payment amount. Please try again.')
                        else:
                            break
                    except ValueError:
                        print('Invalid payment amount. Please try again.')

                # Check payment against price
                if payment == price:
                    print('Thanks for paying!')
                elif payment > price:
                    change = payment - price
                    print(f'Your change is {change:.2f}.')
                else:
                    while True:
                        print('You need to pay more.')
                        additional_payment = input('Please enter the additional amount you wish to pay: ')
                        try:
                            additional_payment = float(additional_payment)
                            if additional_payment <= 0:
                                print('Invalid payment amount. Please try again.')
                            else:
                                break
                        except ValueError:
                            print('Invalid payment amount. Please try again.')
                    total_payment = payment + additional_payment
                    if total_payment >= price:
                        change = total_payment - price
                        print(f'Your change is {change:.2f}.')
                    else:
                        print('Sorry, you did not pay enough.')
                        print('Transaction cancelled.')

                # Update amount of products left
                menu_food.loc[menu_num, 'amount'] -= 1
                print(f'There are now {menu_food.loc[menu_num, "amount"]} {menu_food.loc[menu_num, "food"]} left.')

        # Go back to main menu
        print('')

    # Option 4: Exit
    elif option == '4':
        print('Exiting the program...')
        break

Welcome to the RGyUm fast-food menu. Select an option:
1. Log in (admin only)
2. Add one more product of a certain food (admin only)
3. Buy products
4. Exit

Please enter your username:
Login successful!

Welcome to the RGyUm fast-food menu. Select an option:
1. Log in (admin only)
2. Add one more product of a certain food (admin only)
3. Buy products
4. Exit
You are already logged in as admin.

Welcome to the RGyUm fast-food menu. Select an option:
1. Log in (admin only)
2. Add one more product of a certain food (admin only)
3. Buy products
4. Exit

KeyboardInterrupt: ignored

Keep in mind that I will test your program as many times as I want, with the purpose of "crashing it"! So, be sure you are ready to address all possible input fails! Always check for the correct input, and verify that all error messages are shown correctly. Moreover, ensure that I can execute the options of the program in any order I want!